# Generated by Django 5.1.1 on 2024-10-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_habito_id_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=64)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.BooleanField(default=False)),
                ('id_habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.habito')),
            ],
        ),
    ]
