# Generated by Django 5.1.1 on 2024-10-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='mensaje_motivacional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
